language: scala
scala:
  - 2.13.3

script:
  - sbt clean compile coverage test coverageReport assembly

after_success:
  - sbt coverageReport coveralls

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "target/scala-2.13/mastermind.jar"
  skip_cleanup: true
  on:
    branch: master
